version: "3"

services:
    Router:
        image: handsonsecurity/seed-ubuntu:large
        container_name: seed-router
        tty: true
        cap_add:
                - ALL
        sysctls:
                - net.ipv4.ip_forward=1
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.11
            net-10.8.0.0:
                ipv4_address: 10.8.0.11
        command: bash -c "
                      ip route del default  &&
                      ip route add default via 10.8.0.1 &&
                      iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE &&
                      tail -f /dev/null
                 "
    local-server:
        build: ./image_local_dns_server
        image: seed-local-dns-server
        container_name: local-dns-server-10.9.0.53
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.53
        command: bash -c "
                      ip route del default  &&
                      ip route add default via 10.9.0.11 &&
                      service named start && tail -f /dev/null
                "
                  
    attacker:
        image: handsonsecurity/seed-ubuntu:large
        container_name: seed-attacker
        tty: true
        cap_add:
                - ALL
        privileged: true
        volumes:
                - /home/seed/Desktop/arp:/volumes
        network_mode: host

                  
    User1:
        image: handsonsecurity/seed-ubuntu:large
        container_name: user1-10.9.0.6
        tty: true
        cap_add:
                - ALL
        volumes:
                - /home/seed/Desktop/arp:/volumes
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.6
                
    User2:
        image: handsonsecurity/seed-ubuntu:large
        container_name: user2-10.9.0.7
        tty: true
        cap_add:
                - ALL
        volumes:
                - /home/seed/Desktop/Arp-poisoning:/volumes                
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.7


    attacker-ns:
        build: ./image_attacker_ns
        image: seed-attacker-ns
        container_name: attacker-ns-10.9.0.153
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.153

networks:
    net-10.8.0.0:
        name: net-10.8.0.0
        ipam:
            config:
                - subnet: 10.8.0.0/24

    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24



